# Generated by Django 6.1.1 on 2026-10-03 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='held', max_length=20)),
                ('total_cents', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='events.seat')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(condition=models.Q(('status', 'held')), fields=['expires_at'], name='reservation_held_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', '-created_at'], name='reservation_user_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['held', 'confirmed', 'expired', 'cancelled'])), name='reservation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='reservationseat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('seat',), name='reservation_seat_one_active_per_seat'),
        ),
        migrations.AddConstraint(
            model_name='reservationseat',
            constraint=models.UniqueConstraint(fields=('reservation', 'seat'), name='reservation_seat_unique_in_reservation'),
        ),
    ]
