# Generated by Django 6.1.1 on 2026-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status', 'received')), fields=['received_at'], name='webhook_unprocessed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['received', 'processed', 'failed'])), name='webhook_status_valid')],
            },
        ),
    ]
